version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - uname -a
      - pip install -r requirements.txt
      - apt update
      - apt install -y redis-server
      - /usr/bin/redis-server --port 30073 --requirepass mypassword
  pre_build:
    commands:
  build:
    commands:
      - python -m pytest  --cov=pydis
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar